### PR TITLE
Migrate from webpack to vite

### PR DESCRIPTION
**Pull request by jcushman**
Here's a first cut at migrating from webpack to vite. It does have the potential to break any given JS file, and I only got partway through checking all of the entrypoints, so this would need more testing to merge. Would also want to check how it ends up integrating with whitenoise.

### CODE REVIEW

**Comment by bensteinberg** [comment]
When I run `fab run`, I don't get any JS served at all. Is that the expected behavior? To use the application normally in local development, you have to run `fab run_frontend`?

**Comment by bensteinberg** [comment]
Copying selected text is not working (I assume this is because of the insecure origin):

```
[Vue warn]: Error in v-on handler: "TypeError: navigator.clipboard is undefined"

found in

---> <Sidebar> at static/js/case/sidebar.vue
       <Root> [vue.js:634:16](http://case.test:8080/node_modules/vue/dist/vue.js)
TypeError: navigator.clipboard is undefined
    copyCiteToSelection sidebar.vue:201
    click sidebar.vue:1
    VueJS 33
    mounted sidebar.vue:82
    Lodash 5
    mounted sidebar.vue:75
    VueJS 14
    <anonymous> main.js:9
vue.js:1906:14
​```

**Comment by bensteinberg** [comment]
I'm getting 
```
[Vue warn]: Error in render: "TypeError: this.jurData[this.hoveredSlug] is undefined"

found in

---> <Main> at static/js/homepage-map/main.vue
       <Root> [vue.js:634:16](http://case.test:8080/node_modules/vue/dist/vue.js)
    VueJS 18
    mapMouseover main.vue:155
    VueJS 50
    <anonymous> main.js:9
TypeError: this.jurData[this.hoveredSlug] is undefined
    reporterCount main.vue:172
    render main.vue:1
    VueJS 14
    mapMouseover main.vue:155
    VueJS 50
    <anonymous> main.js:9
vue.js:1906:14
    VueJS 17
    mapMouseover main.vue:155
    VueJS 50
    <anonymous> main.js:9
```
on the main map rollover, but I think this is an artifact of having an incomplete set of cases locally; `fab import_web_volumes` gets some jurisdictions and not others.

**Comment by bensteinberg** [comment]
I don't think the try-catch for loading the analytics JS is working (locally):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://case.test:8080/static/js/analytics.js. (Reason: CORS request did not succeed). Status code: (null).

Module source URI is not allowed in this document: “http://case.test:8080/static/js/analytics.js”. [about:54:1](http://case.test:8000/about/)
Uncaught (in promise) TypeError: error loading dynamically imported module
```

**Comment by jcushman** [comment]
> When I run `fab run`, I don't get any JS served at all. Is that the expected behavior? To use the application normally in local development, you have to run `fab run_frontend`?

Force pushed with settings that should work for `fab run_frontend` (load live assets), `fab run` (load built assets from `static/dist`), and prod mode (load built assets from `staticfiles/dist`).

**Comment by bensteinberg** [comment]
To confirm the semi-obvious, there's no `vite` on the command line -- you can run `npx vite`, I think, but the canonical way to run a build by hand would be `yarn build` (which is actually running `yarn run vite build`) -- is all that correct?

**Comment by bensteinberg** [comment]
I see several templates that `{% load capweb_static %}` without actually using the tag. It's probably not critical, but I think we can remove it in
```
capweb/templates/file_download.html
cite/templates/cite/case_editor.html
cite/templates/cite/citations.html
```
unless I'm missing something.

**Comment by bensteinberg** [comment]
Same as above, but for the `static` template tag; these files load it but don't use it:
```
./capweb/templates/tools.md
./capweb/templates/file_download.html
./capweb/templates/exhibits/cite-grid.html
./capweb/templates/layouts/base.html
./capweb/templates/layouts/extended.html
./capweb/templates/includes/footer.html
./capweb/templates/gallery/gallery_section.html
./capweb/templates/gallery/gallery.html
./capweb/templates/includes/nav.html
./labs/templates/labs-about.md
./cite/templates/cite/citations.html
./cite/templates/cite/case_editor.html
```
Again, I may be missing something. I got this list with 
```
for FILE in `rg --files-with-matches 'load static' .` ; do rg --files-without-match '\{% static' $FILE ; done
```

**Pull request merged**
