### PR TITLE
unautoescaped output on error_page

### PR DESCRIPTION
**Pull request by ChefAndy**
Addresses: #1412

### CODE REVIEW

**Comment by jcushman** [comment]
This needs a little more digging -- error page output is weird in Django because of a series of security bugs involving injecting JS into custom error responses. Want to make sure we're not undoing that.

**Comment by bensteinberg** [comment]
I think you still have debugging code at line 303... ;)

**Comment by ChefAndy** [comment]
> I think you still have debugging code at line 303... ;)

Whoops— missed a commit in that push.

**Comment by ChefAndy** [comment]
We'll try this later.

**Comment by ChefAndy** [comment]
Hmm... worked locally. Let's try that again.

**Pull request merged**
