### PR TITLE
Update Elasticsearch

### PR DESCRIPTION
**Pull request by bensteinberg**
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.16.html

### CODE REVIEW

**Comment by mdellabitta** [comment]
Looks like changes made to make CAP export happy blew this up, but I don't think it matters?

**Comment by bensteinberg** [comment]
I'm looking into why the last updated rewrite isn't working.

**Comment by bensteinberg** [comment]
last_updated is fine, the problem is with date_added

**Comment by rebeccacremona** [comment]
Ah, nice catch! In case others in the future are looking: that 23-12-05 date is simply the last time these files were generated
image

**Review by rebeccacremona — APPROVED** [review]
LGTM!

**Pull request merged**
