### PR TITLE
Add regexes

### PR DESCRIPTION
**Pull request by bensteinberg**
Thanks for the regexes, @jcushman. 

What I want here is something like a list comprehension for `Q() | ...`

### CODE REVIEW

**Comment by bensteinberg** [comment]
Ah, maybe `reduce(operator.or_,`, will try it.

**Comment by bensteinberg** [comment]
Thanks for the edit -- I thought the A should get an X, too?

**Comment by jcushman** [comment]
Aw dang. Yeah I think it actually wants to be "AXX-XXXXXXXXX" -- the A is analogous to the dashes.

**Comment by bensteinberg** [comment]
Ah, OK. I guess, like with SSNs, we are not concealing that this is a masked A number. I'll put in another PR unless you're already working on one.

**Comment by jcushman** [comment]
Go for it -- thanks!

**Pull request merged**
