### PR TITLE
Bump Postgres to 11.17

### PR DESCRIPTION
**Pull request by bensteinberg**

### CODE REVIEW

**Comment by bensteinberg** [comment]
https://www.postgresql.org/docs/release/11.17/

**Review by matteocargnelutti — APPROVED** [review]
LGTM 🤖

**Comment by bensteinberg** [comment]
Thanks, LG except for the image not being present... stay tuned.

**Comment by matteocargnelutti** [comment]
```
ERROR: failed to solve: postgres:11.17: docker.io/library/postgres:11.17: not found
```

☝️  Besides this of course, but I am pretty sure this exactly what you're working on right now 😄 .

**Pull request merged**
