### PR TITLE
Install rum and temporal_tables in the docker container

### PR DESCRIPTION
**Pull request by bensteinberg**

### CODE REVIEW

**Comment by bensteinberg** [comment]
After blasting and recreating the data volume:
```
docker-compose down
docker volume rm capstone_db_data
docker-compose up -d --build
docker-compose exec db psql --user=postgres -c "CREATE DATABASE capdb;"
docker-compose exec db psql --user=postgres -c "CREATE DATABASE capapi;"
docker-compose exec web fab init_dev_db
docker-compose exec web fab load_test_data
docker-compose exec web fab update_all_snippets
```
I get
```
$ docker-compose exec db psql capdb --user=postgres -c "SELECT * from pg_extension"
     extname     | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-----------------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql         |       10 |           11 | f              | 1.0        |           | 
 pg_trgm         |       10 |         2200 | t              | 1.3        |           | 
 rum             |       10 |         2200 | t              | 1.1        |           | 
 temporal_tables |       10 |         2200 | t              | 1.2.0      |           | 
 plv8            |       10 |           11 | f              | 1.4.10     |           | 
(5 rows)
```

**Review by rebeccacremona — APPROVED** [review]
Oh fantastic! 

`USE_PGXS=1` is interetsing; that might be the thing that prevented my attempts to get temporal tables working

**Comment by bensteinberg** [comment]
I looked for a slicker way to set an env var per layer, but this seems fine.

**Comment by rebeccacremona** [comment]
Seems plenty slick to me!

**Pull request merged**
