### PR TITLE
Addition - Public Bulk Data - Dataverse + Kaggle

### PR DESCRIPTION
**Pull request by lkfitz**
Addition to highlight bulk data availability on Harvard Dataverse and Kaggle.

### CODE REVIEW

**Comment by anastasia** [comment]
Tiniest nitpick: would you mind adding target="_blank" to those links so that they open in new tabs instead of taking the user away from the cap site?

**Comment by bensteinberg** [comment]
I think the `p` tag probably needs to be in a `div`, and I'm not sure this is the right page for this content, in any case. Maybe a subsection in https://case.law/bulk/ ?

**Comment by lkfitz** [comment]
Sounds good! I'll whip this up as a subsection on https://case.law/bulk/ and we can revisit.

**Comment by lkfitz** [comment]
Here's my attempt at a subsection! Feedback encouraged https://github.com/harvard-lil/capstone/pull/749

**Comment by rebeccacremona** [comment]
(Closed by request; see #749 )

**Pull request closed without merging**
